language: python
services: docker

env:
  global:
    - ROLE_NAME: install-monit-from-source
  matrix:
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: ubuntu1604
    - MOLECULE_DISTRO: debian9
    - MOLECULE_DISTRO: debian10

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq python-apt python
- sudo -H pip install --upgrade urllib3[secure] pyopenssl

install:
- pip install molecule docker ansible

before_script:
- cd ../
- mv ansible-role-$ROLE_NAME jpartain89.$ROLE_NAME
- cd jpartain89.$ROLE_NAME

script:
- molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: n1W+FtJRK8Wr5LvP88qHkeXxRhugnoV7gaYUys4E1Np/1icGUtLZiS6dfclruU0wA5MERKCOXL3PKSA605DWFVhRFlHu7yaf+8pyN9ZAEKrgx6AAHW1b7XJgSzjeQxfA0BKOMxsjNS3oEfamIL50DEy1GvgDfYMdktBGE9l4Y0xuMy3VDot8+HI5EYnE6nhe3EgcOaENv/BDADimnc9iPfJCZahIAmFVEfUCYap0B65exh4c3wxxWKor98LkqbG1C2MYsB76tHxwy3L35GNKIfJep7OpcfdduNimyLhdgb/u6T2qQH/OlfeZ4/Gz32N7o3RHwLh/PVUJJRwpDRGH+tNanJ5471dg+sWGjAXK3/U9NmSnYPK1cAbHwKKE9z+KA47OV45j4TdGC5sXIam1JzYGnUL8e7MsKBMzCIHbGqrNSdGbtfMnOXAtlJf5URQloc/lVMaN8VJ/qpNnzBTvWWfC2Mfiu0jH6CloQ516I+oJtim9FUAYZwlGDYrZ7gLJIN/yWlZ2FHPi3ROQ6NbPp9y4YYWYkDc8DD46204wOk5r0W1mQvUDwl8DVvsXG/2IRgxchg11M8TX3IDlUcDwYo1SH7TiTWwP8KRpd3elET9MFFbHl4Gtxt/UsNnYjFbVW75aK9se6uPdrp/sqin54L03ZRCjszNj15H173imxu8=
