---
# monit_from_source/tasks/main.yml

- name: Include Debian vars
  include_vars: debian.yml
  when: ansible_os_family == "Debian"

- name: Get Current Monit Version
  shell: "{{ monit_executable }} --version | awk 'NR==1 {print $5}'"
  register: _current_monit_version
  ignore_errors: "yes"
  changed_when: false

- name: Add Backports apt repo for CheckInstall
  apt_repository:
    repo: "deb http://deb.debian.org/debian buster-backports main contrib non-free"
    state: present
  become: true
  when:
    - ansible_facts['distribution_release'] == "buster"
    - ansible_facts['lsb']['id']  != "Raspbian"

- name: Install Required Programs to Build Monit
  apt:
    name: "{{ monit_apt_apps }}"
    state: present
    update_cache: yes
    cache_valid_time: "{{ cache_valid_time_var }}"
  become: true
  when: ansible_os_family == "Debian"

- name: Create Any Missing Directories for Monit's Git Repo
  file:
    path: "{{ monit_git_repo_dest }}"
    state: directory
    mode: 0775
  become: false
  #become_user: "{{ ansible_user_id }}"

- name: Clone/Update Monit's Git Repo
  git:
    repo: "{{ monit_git_repo_http }}" # noqa 401
    dest: "{{ monit_git_repo_dest }}"
    update: yes
    force: yes
  register: monit_git_update
  become: true
  become_user: "{{ ansible_user_id }}"

- name: Set Current Version from Git Repo
  shell: awk '$1=="Version"{print $2;exit;}' ./CHANGES
  args:
    chdir: "{{ monit_git_repo_dest }}"
  register: _git_monit_version
  changed_when: false

- name: Build Monit
  include_tasks: monit_build.yml
  when: _current_monit_version.stdout_lines != _git_monit_version.stdout_lines
  register: _monit_build

- name: Monit Autostart
  include_tasks: monit_autostart.yml
