---
# monit_from_source/tasks/main.yml

- name: Monit | Debian | Install Required Programs to Build Monit
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: "{{ cache_valid_time_var }}"
  with_items:
    - "{{ monit_apt_apps }}"
  become: true
  when: ansible_os_family == "Debian"

- name: Monit | macOS | Install Required Programs to Build Monit
  homebrew:
    name: "{{ item }}"
    state: latest
    update_homebrew: yes
  with_items:
    - "{{ monit_brew_apps }}"
  when: ansible_os_family == "Darwin"

- name: Clone/Update Monit's Git Repo
  git:
    repo: "{{ monit_git_repo_http }}"
    dest: "{{ monit_git_repo_dest }}"
    update: yes
  register: monit_git_update
  become: false
  become_user: jpartain89

- include: monit_build.yml
#  when: monit_git_update|changed
