---
# monit/tasks/monit_config.yml

- name: Create Monit Directory
  file:
    path: /etc/monit
    owner: root
    group: root
    state: directory
    mode: 0775

- name: Create Monit DIr's
  file:
    path: /etc/monit/conf.d
    state: directory
    owner: root
    group: root
    mode: 0775

- name: Link Monit conf Files
  file:
    src: "{{ monit_conffiles_loc }}/{{ item }}"
    dest: /etc/monit/conf.d/{{ item }}
    state: link
  with_items:
    - conf.d/{{ monit_conf_files }}
    - templates
    - scripts
    - alert_defaults

- name: Link Personal Monit Directories
  file:
    src: "{{ monit_conffiles_loc }}/{{ item }}"
    dest: /etc/monit/{{ item }}
    state: link
  with_items:
    - alert_defaults
    - scripts

- name: Build out monitrc
  template:
    src: monitrc.j2
    dest: /etc/monitrc
    owner: root
    group: root
    mode: 0700
  become: true
