---
# monit/tasks/build_monit.yml

- name: Bootstrapping
  shell: './bootstrap'
  args:
    chdir: "{{ monit_git_repo_dest }}"
  environment:
    PATH: "/usr/local/bin:/usr/local/sbin:{{ ansible_env.PATH }}"

- name: Configure
  shell: './configure {{ monit_configure_options }}'
  args:
    chdir: "{{ monit_git_repo_dest }}"

- name: Make
  shell: 'make'
  args:
    chdir: "{{ monit_git_repo_dest }}"

- name: Debian | sudo checkinstall
  shell: 'checkinstall -y --pkgversion $(awk '/Version/{print $NF}' ./CHANGES  | head -1)'
  args:
    chdir: "{{ monit_git_repo_dest }}"
  become: true
  register: _checkinstall_monit
  when: ansible_os_family == "Debian"

- name: macOS | sudo make install
  make:
    chdir: "{{ monit_git_repo_dest }}"
    target: install
  when: ansible_os_family != "Debian"
  register: _makeinstall_monit

- debug: var=_checkinstall_monit
- debug: var=_makeinstall_monit

- name: Debian | Hold Monit Package
  dpkg_selections:
    name: monit
    selection: hold
  when: ansible_os_family == "Debian"
  become: true

- name: Run make cleanall
  shell: 'make cleanall'
  args:
    chdir: "{{ monit_git_repo_dest }}"
  become: true
