---

- name: Converge
  hosts: all

  pre_tasks:
    - name: Install Required Apps
      apt:
        name: lsb-release
        state: present
        update_cache: yes
      become: true

  roles:
    - role: install-monit-from-source
